/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminal_pv;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Luis Fm
 */
public class Contenedor extends javax.swing.JFrame {

    String datos[]={"Aviso #1","Aviso #2","Aviso #3"};
     JPanel FixedPanel = new JPanel(new GridBagLayout());
    /**
     * Creates new form Contenedor
     */
    public Contenedor() {  
        
        FixedPanel.setName("Login");
        FixedPanel.setPreferredSize(this.getSize());
        FixedPanel.setBackground(  new Color(224, 224, 224));
        
        
        
       
        initComponents();
        
        FixedPanel.add(new Login(FixedPanel,dateFecha));
        this.add(FixedPanel);
        
        this.setLocationRelativeTo(null);        
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/icono.png"));
        setIconImage(icon);   
        setVisible(true);
        
        texto.setText("");
        texto.setOpaque(false);
        
        date();
        //setTitulos();

    }
    
    public void setTitulos (){
    
         Thread t = new Thread(new Runnable() {
            
            String txt ="";
            int i=0, c;
            
            
            @Override
            public void run() {
                while(true){  
            
                    if(c<30){
                        
                        c++;
                        for (int j = 0; j < datos.length; j++) {
                            String var=datos[j];
                            for (int k = var.length()-1; k > -1; k--) {
                               if(getPanel()){
                                    txt= var.charAt(k)+txt;
                                    texto.setText(txt);
                                }else{ texto.setText(""); }
                                try {
                                    Thread.sleep(100);                 
                                } catch(InterruptedException ex) {
                                    Thread.currentThread().interrupt();
                                }
                            }

                            for (int k = 0; k < 25; k++) {
                                
                                if(getPanel()){
                                    txt=" "+txt;
                                    texto.setText(txt);
                                }
                                
                                
                                try {
                                    Thread.sleep(100);                 
                                } catch(InterruptedException ex) {
                                    Thread.currentThread().interrupt();
                                }
                            }
                        }
                    }else{
                        c=0;
                        txt="";
                    }
                }
                       
                    
                                  
                
            }     
        });
        t.start();
    
    
    }
    
    
    
    
     //Imprime fecha
    public void date(){
         Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){                            
                    Calendar c1 = GregorianCalendar.getInstance();        
                    dateFecha.setText(c1.getTime().toLocaleString()+" ");
                    try {Thread.sleep(1000);}
                    catch(InterruptedException e) {}      
                }
            }     
        });
        t.start();        
    }
    
    public boolean getPanel(){
        
        if(FixedPanel.getComponentCount() >0){        
            return !FixedPanel.getName().equals("Login");       
        }
        else return false;
    }
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        texto = new javax.swing.JTextField();
        dateFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Terminal_PV");
        setMinimumSize(new java.awt.Dimension(880, 600));

        jPanel2.setBackground(new java.awt.Color(224, 224, 224));
        jPanel2.setOpaque(false);

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(224, 224, 224));
        texto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texto.setText("Esto es de prueba");
        texto.setBorder(null);
        texto.setFocusable(false);
        texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoMouseClicked(evt);
            }
        });

        dateFecha.setBackground(new java.awt.Color(255, 255, 255));
        dateFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateFecha.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(dateFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 3) {
            
        } else if (evt.getClickCount() == 2) {
        ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
        scheduler.scheduleAtFixedRate( 
            new Runnable() 
            {
                @Override
                public void run() {                   
                   
                }
              }, 500, 50 , TimeUnit.MILLISECONDS );
        
            this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            this.toFront();
            
        }
    }//GEN-LAST:event_textoMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateFecha;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
