/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminal_pv;

import database.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Luis Fm
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    JPanel content;
    String idU, nameU, userU, passU, roleU;
    JLabel fecha;
    
    public Login(JPanel x, JLabel fecha) {
        content = x;
        
        initComponents();
        
        ImageIcon icono = new ImageIcon ("src/iconos/icono.png");
        foto.setIcon(new ImageIcon(icono.getImage().getScaledInstance(100,90,Image.SCALE_SMOOTH)));
        icono = new ImageIcon ("src/iconos/user.png");
        use.setIcon(new ImageIcon(icono.getImage().getScaledInstance(30,30,Image.SCALE_SMOOTH)));
        icono = new ImageIcon ("src/iconos/pass.png");
        pas.setIcon(new ImageIcon(icono.getImage().getScaledInstance(30,30,Image.SCALE_SMOOTH)));   
        
        this.fecha = fecha;
       
    }
    
    public void paint(Graphics g){
        
        Dimension size = getSize();
        ImageIcon image = new ImageIcon("src/iconos/fondo.png");
        g.drawImage(image.getImage(), 0, 0, size.width,size.height,null);
        setOpaque(false);
        super.paint(g);
    }   

    
    public boolean verifyUser(String user){
        boolean res=false;
        
        Conexion con = new Conexion();
        ResultSet rs = con.select("SELECT id, full_name, user, pass, role FROM users WHERE user='"+user+"';"); 
        try { while(rs.next()){   
                idU = rs.getString(1);
                nameU = rs.getString(2);                
                userU = rs.getString(3);
                passU = rs.getString(4);
                roleU = rs.getString(5);
            } 
        }catch(SQLException ex){}   
         
        con.desconectar();
        
        
        if(user.trim().equals(userU)){
               res=true;
        }        
        return res;
    }
    
    public boolean verifyPass(String pass){
        boolean res=false;      
        
        if(pass.trim().equals(passU)){
               res=true;  
        }
        return res;
    }
    
    public void loginUser(){
            
        if(verifyUser(name.getText())){
            error.setText(""); 
            if(verifyPass(pass.getText())){            
                error.setText("");
                content.removeAll();
                content.setLayout(new GridLayout());
                content.setPreferredSize(this.getSize());
                content.setBackground( new Color(224, 224, 224) );
                String []datos={idU, nameU, userU, passU, roleU}; 
                
                
                
                content.add(new Start(content, datos, fecha));
                content.setName("Start");
                content.repaint();
                
            }else{
                if(pass.getText().length()!=0 && pass.getText().equals("1234567890")){
                    pass.grabFocus();                    
                }else{
                    error.setText("** Contraseña incorrecta");                    
                    if(error.getText().equals("** Contraseña incorrecta")){
                        pass.setText("");
                        pass.setForeground(new Color(0, 0, 0));
                    }
                    pass.grabFocus();                
                }
                
            }        
        }else{           
            if( !name.getText().equals("Username")){
                error.setText("** Usuario incorrecto");
                name.grabFocus();
            }
        }
        
        content.revalidate();
        content.repaint();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        pas = new javax.swing.JLabel();
        use = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        foto.setBackground(new java.awt.Color(204, 204, 204));
        foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto.setText(" ");
        jPanel4.add(foto, new java.awt.GridBagConstraints());

        jPanel1.setOpaque(false);

        jButton1.setText("Log In");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name.setColumns(10);
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setText("Username");
        name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        pass.setForeground(new java.awt.Color(204, 204, 204));
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setText("1234567890");
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passKeyTyped(evt);
            }
        });

        pas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        use.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(use, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(use, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if(name.getText().equals("Username")){
             name.setText("");
             name.setForeground(new Color(0, 0, 0));
        }        
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if(name.getText().length()==0 || name.getText().equals("Username")){
             name.setForeground(new Color(204, 204, 204));
             name.setText("Username");
        }else{
             name.setForeground(new Color(0, 0, 0));          
        }
        
       
    }//GEN-LAST:event_nameFocusLost

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
         if(pass.getText().equals("1234567890")){
             pass.setText("");
             pass.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        // TODO add your handling code here:
        if(pass.getText().length()==0 || pass.getText().equals("1234567890")){
             pass.setForeground(new Color(204, 204, 204));
             pass.setText("1234567890");
        }else{
             pass.setForeground(new Color(0, 0, 0));          
        }
    }//GEN-LAST:event_passFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loginUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:    
        loginUser();
    }//GEN-LAST:event_passActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        loginUser();
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(name.getText().length() == 10){
            evt.consume(); //getToolkit().beep();
        }else 
            if(!Character.isLetter(c) && !Character.isDigit(c)){
                 evt.consume(); //getToolkit().beep();
            }
    }//GEN-LAST:event_nameKeyTyped

    private void passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(pass.getText().length() == 10){
            evt.consume(); //getToolkit().beep();
        }else 
            if(!Character.isLetter(c) && !Character.isDigit(c)){
                 evt.consume(); //getToolkit().beep();
            }
        
    }//GEN-LAST:event_passKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField name;
    private javax.swing.JLabel pas;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel use;
    // End of variables declaration//GEN-END:variables
}
